server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Maxahup/data.git
          search-paths: config-data
  application:
    name: MS-config-service
